
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Aug 05 21:08:31 BOT 2020
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 18;
  public static final int Class = 32;
  public static final int Llave_c = 25;
  public static final int Op_booleano = 21;
  public static final int Llave_a = 24;
  public static final int If = 5;
  public static final int Identificador_Var = 42;
  public static final int T_dato = 10;
  public static final int Else = 6;
  public static final int Op_Restar = 36;
  public static final int Corchete_c = 27;
  public static final int Corchete_a = 26;
  public static final int Op_Sumar = 37;
  public static final int Assign = 41;
  public static final int Return = 39;
  public static final int While = 8;
  public static final int Op_Potencia = 33;
  public static final int Division = 16;
  public static final int Int = 3;
  public static final int Cadena = 4;
  public static final int Parentesis_c = 23;
  public static final int Parentesis_a = 22;
  public static final int For = 9;
  public static final int EOF = 0;
  public static final int P_coma = 29;
  public static final int error = 1;
  public static final int Linea = 2;
  public static final int Memb_Access = 40;
  public static final int Op_Multiplicar = 35;
  public static final int Op_atribucion = 19;
  public static final int Print = 38;
  public static final int Do = 7;
  public static final int ERROR = 31;
  public static final int Op_logico = 17;
  public static final int Op_Dividir = 34;
  public static final int Power = 43;
  public static final int Identificador = 30;
  public static final int Resta = 14;
  public static final int Multiplicacion = 15;
  public static final int Op_incremento = 20;
  public static final int Numero = 44;
  public static final int Suma = 13;
  public static final int Main = 28;
  public static final int Igual = 12;
  public static final int Comillas = 11;
}

